# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  database: whiteboard
  username: dbuser
  password: nuggets6
  host: 10.254.4.97
  
development: &development
  adapter: mysql2
  database: whiteboard
  username: dbuser
  password: nuggets6
  host: 10.254.4.97
